//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bus()
        {
            this.busowners = new HashSet<busowner>();
            this.users = new HashSet<user>();
            this.bookedseats1 = new HashSet<bookedseat>();
            this.busroutes = new HashSet<busroute>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string OwnerName { get; set; }
        public Nullable<int> BookedSeats { get; set; }
        public string Source { get; set; }
        public string Destination { get; set; }
        public string DriverName { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> TotalSeats { get; set; }
        public Nullable<int> UpperSeats { get; set; }
        public Nullable<int> LowerSeats { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<busowner> busowners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user> users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bookedseat> bookedseats1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<busroute> busroutes { get; set; }
    }
}
