//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BusDBEntities : DbContext
    {
        public BusDBEntities()
            : base("name=BusDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<bookedseat> bookedseats { get; set; }
        public virtual DbSet<bus> buses { get; set; }
        public virtual DbSet<busowner> busowners { get; set; }
        public virtual DbSet<busroute> busroutes { get; set; }
        public virtual DbSet<route> routes { get; set; }
        public virtual DbSet<seat> seats { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
