//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class busowner
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> BusId { get; set; }
        public Nullable<int> ApprovedByAdmin { get; set; }
    
        public virtual bus bus { get; set; }
        public virtual admin admin { get; set; }
    }
}
