//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class busroute
    {
        public int Id { get; set; }
        public Nullable<int> BusId { get; set; }
        public Nullable<int> RouteId { get; set; }
    
        public virtual route route { get; set; }
        public virtual bus bus { get; set; }
    }
}
